"""``lit export`` — project the vault out to a .bib file (M12.1).

The vault's metadata.yaml files are the single source of truth; this
command renders a derived ``.bib`` so LaTeX can ``\\cite{paper-id}``.
Cite key == paper id, which is filesystem-safe and bibtex-legal.

The command is deliberately explicit: ``--project NAME`` or ``--all``
(mutually exclusive, no default) so the user can never accidentally
flatten the wrong subset of their library into a file. A sentinel
comment as the first line of every generated .bib also stops repeated
runs from overwriting a hand-edited ``references.bib`` that happens to
share the same path.

Filter semantics match ``lit list`` for the equality-style fields, with
one extension: ``--priority`` / ``--status`` / ``--year`` accept a
comma-separated list to express OR-within-field. Filters across
different flags are AND-combined as usual.

Future formats (RIS / CSL-JSON) live behind the ``--format`` flag,
which is reserved but only ``bibtex`` is implemented in M12.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import click
from rich.console import Console

from litman import __version__
from litman.core.document import list_papers
from litman.core.library import find_vault, resolve_library_or_vault
from litman.exceptions import ExportError
from litman.exporters.bibtex import emit_bib, has_sentinel

console = Console()

# Default filename when ``-o`` is not given. Matches the common LaTeX
# convention of pairing ``\bibliography{refs}`` with ``refs.bib``.
_DEFAULT_OUTPUT = "refs.bib"


def _now_iso() -> str:
    """Local-timezone ISO 8601 timestamp with seconds precision."""
    return datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")


def _build_sentinel(timestamp: str | None = None) -> str:
    """Return the first-line comment that marks a litman-generated .bib.

    Format is intentionally human-readable; ``has_sentinel`` only
    matches the leading prefix, so the version + timestamp can evolve
    without breaking detection.
    """
    ts = timestamp or _now_iso()
    return (
        f"% Generated by litman v{__version__} on {ts}. "
        "Do not hand-edit — re-run `lit export`."
    )


def _split_csv(value: str | None) -> list[str] | None:
    """Parse a comma-separated CLI value into a list of trimmed tokens.

    Returns ``None`` (meaning "no filter") when ``value`` is ``None`` or
    empty. Empty tokens after splitting (e.g. trailing comma) are
    discarded silently rather than triggering an error; this matches
    the "be permissive in what you accept" CLI norm.
    """
    if value is None:
        return None
    tokens = [t.strip() for t in value.split(",") if t.strip()]
    return tokens or None


def _matches_filters(paper: dict[str, Any], filters: dict[str, list[str] | None]) -> bool:
    """Return True iff the paper matches every non-None filter.

    Within a single filter (e.g. ``--priority A,B``), values are
    OR-combined. Across different filters, values are AND-combined.
    """
    project = filters.get("project")
    if project is not None:
        # --project is single-valued (it identifies one project context),
        # so we treat it as a regular list-membership check.
        paper_projects = paper.get("projects") or []
        if not any(p in paper_projects for p in project):
            return False

    for key, field in (("priority", "priority"), ("status", "status"), ("type", "type")):
        wanted = filters.get(key)
        if wanted is None:
            continue
        if str(paper.get(field) or "") not in wanted:
            return False

    years = filters.get("year")
    if years is not None:
        paper_year = paper.get("year")
        # Compare as strings; --year accepts comma-separated ints/strings.
        if paper_year is None or str(paper_year) not in years:
            return False

    return True


@click.command("export")
@click.option(
    "--project",
    "project",
    default=None,
    help=(
        "Project name (as registered in lit-config.yaml) whose linked "
        "papers should be exported. Mutually exclusive with --all."
    ),
)
@click.option(
    "--all",
    "export_all",
    is_flag=True,
    default=False,
    help=(
        "Export every paper in the vault. Mutually exclusive with --project. "
        "One of --project / --all is required."
    ),
)
@click.option(
    "-o", "--output",
    "output_path",
    type=click.Path(file_okay=True, dir_okay=False, path_type=Path),
    default=None,
    help=(
        "Output file. Defaults to ./refs.bib in the current working "
        "directory."
    ),
)
@click.option(
    "--priority",
    default=None,
    help=(
        "Comma-separated list of priorities to include "
        "(e.g. `--priority A,B`). Within the flag values are OR-combined; "
        "across flags they are AND-combined."
    ),
)
@click.option(
    "--status",
    default=None,
    help="Comma-separated list of statuses (e.g. `--status deep-read,skim`).",
)
@click.option(
    "--year",
    default=None,
    help="Comma-separated list of years (e.g. `--year 2023,2024`).",
)
@click.option(
    "--type",
    "type_filter",
    default=None,
    help="Comma-separated list of editorial types (research/review/...).",
)
@click.option(
    "--force",
    is_flag=True,
    default=False,
    help=(
        "Overwrite the target file even if it does not carry the litman "
        "sentinel (typically a hand-edited references.bib)."
    ),
)
@click.option(
    "--format",
    "fmt",
    type=click.Choice(["bibtex"], case_sensitive=False),
    default="bibtex",
    show_default=True,
    help="Output format. Reserved for future formats; only `bibtex` works in M12.",
)
@click.option(
    "--library",
    type=click.Path(file_okay=False, dir_okay=True, path_type=Path),
    default=None,
    envvar="LIT_LIBRARY",
    help="Vault path. Defaults to $LIT_LIBRARY or cwd-walk discovery.",
)
@click.option(
    "--vault",
    "vault_name",
    default=None,
    help=(
        "Vault name from ~/.config/litman/vaults.yaml (M8). "
        "Mutually exclusive with --library."
    ),
)
def export_cmd(
    project: str | None,
    export_all: bool,
    output_path: Path | None,
    priority: str | None,
    status: str | None,
    year: str | None,
    type_filter: str | None,
    force: bool,
    fmt: str,
    library: Path | None,
    vault_name: str | None,
) -> None:
    """Project the vault out to a .bib file (M12).

    Cite keys equal paper ids, so a freshly-exported bibliography
    works with ``\\cite{<paper-id>}`` immediately. Re-running the
    command on the same file is the supported update path.
    """
    if export_all and project is not None:
        raise ExportError(
            "--project and --all are mutually exclusive. Pass exactly one."
        )
    if not export_all and project is None:
        raise ExportError(
            "Pass --project <name> or --all. Refusing to export with no scope "
            "(would silently flatten the whole vault into a single .bib)."
        )

    # fmt is reserved for future formats; M12 only ships bibtex. Click's
    # Choice already restricts the surface, so this is a defensive check.
    if fmt != "bibtex":  # pragma: no cover — Click prevents it today
        raise ExportError(f"Unsupported export format: {fmt!r}.")

    vault = find_vault(resolve_library_or_vault(library, vault_name))
    all_papers = list_papers(vault)

    filters: dict[str, list[str] | None] = {
        "project": [project] if project is not None else None,
        "priority": _split_csv(priority),
        "status": _split_csv(status),
        "year": _split_csv(year),
        "type": _split_csv(type_filter),
    }
    selected = [p for p in all_papers if _matches_filters(p, filters)]
    # Sort by id for stable output (matches INDEX.json convention).
    selected.sort(key=lambda p: str(p.get("id", "")))

    target = (output_path or Path.cwd() / _DEFAULT_OUTPUT).resolve()

    # Sentinel-guarded overwrite: an existing target without our sentinel
    # is treated as user-owned and refused unless --force is given.
    if target.exists() and not force:
        existing = target.read_text(encoding="utf-8", errors="replace")
        if not has_sentinel(existing):
            raise ExportError(
                f"Refusing to overwrite {target}: file has no litman "
                "sentinel (looks hand-edited). Pass --force to overwrite "
                "anyway, or write to a different path with -o."
            )

    sentinel = _build_sentinel()
    content = emit_bib(selected, sentinel)

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")

    scope = f"project={project!r}" if project else "all papers"
    console.print(
        f"[green]✓[/] Exported {len(selected)} paper"
        f"{'s' if len(selected) != 1 else ''} ({scope}) → "
        f"[bold]{target}[/]"
    )
    if not selected:
        # Not an error — an empty bib is a valid state (e.g. brand-new
        # project with no linked papers yet). Hint the user, though.
        console.print(
            "[dim]Note: no papers matched. The .bib has only the sentinel "
            "comment line.[/]"
        )
