"""``lit export`` — project the vault out to a .bib file (M12.1).

The vault's metadata.yaml files are the single source of truth; this
command renders a derived ``.bib`` so LaTeX can ``\\cite{paper-id}``.
Cite key == paper id, which is filesystem-safe and bibtex-legal.

The command is deliberately explicit: ``--project NAME`` or ``--all``
(mutually exclusive, no default) so the user can never accidentally
flatten the wrong subset of their library into a file. A sentinel
comment as the first line of every generated .bib also stops repeated
runs from overwriting a hand-edited ``references.bib`` that happens to
share the same path.

Filter semantics match ``lit list`` (shared via ``core.query``):
``--priority`` / ``--status`` / ``--year`` / ``--type`` / ``--topic`` /
``--method`` / ``--data`` / ``--author`` each accept a comma-separated
list to express OR-within-field, and filters across different flags are
AND-combined.

Future formats (RIS / CSL-JSON) live behind the ``--format`` flag,
which is reserved but only ``bibtex`` is implemented in M12.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import click
from rich.console import Console

from litman import __version__
from litman.core.document import list_papers
from litman.core.library import find_vault, resolve_library_or_vault
from litman.core.query import matches_filters, split_csv
from litman.exceptions import ExportError
from litman.exporters.bibtex import emit_bib, has_sentinel

console = Console()

# Default filename when ``-o`` is not given. Matches the common LaTeX
# convention of pairing ``\bibliography{refs}`` with ``refs.bib``.
_DEFAULT_OUTPUT = "refs.bib"


def _now_iso() -> str:
    """Local-timezone ISO 8601 timestamp with seconds precision."""
    return datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")


def _build_sentinel(timestamp: str | None = None) -> str:
    """Return the first-line comment that marks a litman-generated .bib.

    Format is intentionally human-readable; ``has_sentinel`` only
    matches the leading prefix, so the version + timestamp can evolve
    without breaking detection.
    """
    ts = timestamp or _now_iso()
    return (
        f"% Generated by litman v{__version__} on {ts}. "
        "Do not hand-edit — re-run `lit export`."
    )


@click.command("export")
@click.option(
    "--project",
    "project",
    default=None,
    help=(
        "Project name (as registered in lit-config.yaml) whose linked "
        "papers should be exported. Mutually exclusive with --all."
    ),
)
@click.option(
    "--all",
    "export_all",
    is_flag=True,
    default=False,
    help=(
        "Export every paper in the vault. Mutually exclusive with --project. "
        "One of --project / --all is required."
    ),
)
@click.option(
    "-o", "--output",
    "output_path",
    type=click.Path(file_okay=True, dir_okay=False, path_type=Path),
    default=None,
    help=(
        "Output file. Defaults to ./refs.bib in the current working "
        "directory."
    ),
)
@click.option(
    "--priority",
    default=None,
    help=(
        "Comma-separated list of priorities to include "
        "(e.g. --priority A,B). Within the flag values are OR-combined; "
        "across flags they are AND-combined."
    ),
)
@click.option(
    "--status",
    default=None,
    help="Comma-separated list of statuses (e.g. --status deep-read,skim).",
)
@click.option(
    "--year",
    default=None,
    help="Comma-separated list of years (e.g. --year 2023,2024).",
)
@click.option(
    "--type",
    "type_filter",
    default=None,
    help="Comma-separated list of editorial types (research/review/...).",
)
@click.option(
    "--topic",
    default=None,
    help="Comma-separated list of topics; a paper matches if any topic "
         "is in its topics list (within the flag OR, across flags AND).",
)
@click.option(
    "--method",
    default=None,
    help="Comma-separated list of methods (matched against the methods list).",
)
@click.option(
    "--data",
    "data_filter",
    default=None,
    help="Comma-separated list of datasets (matched against the data list).",
)
@click.option(
    "--author",
    default=None,
    help="Comma-separated author cues; case-insensitive substring match "
         "against any author entry.",
)
@click.option(
    "--force",
    is_flag=True,
    default=False,
    help=(
        "Overwrite the target file even if it does not carry the litman "
        "sentinel (typically a hand-edited references.bib)."
    ),
)
@click.option(
    "--format",
    "fmt",
    type=click.Choice(["bibtex"], case_sensitive=False),
    default="bibtex",
    show_default=True,
    help="Output format. Reserved for future formats; only bibtex is currently implemented.",
)
@click.option(
    "--library",
    type=click.Path(file_okay=False, dir_okay=True, path_type=Path),
    default=None,
    envvar="LIT_LIBRARY",
    help="Override the active vault. Discovery order: this flag / $LIT_LIBRARY, then the active registered vault, then cwd-walk.",
)
@click.option(
    "--vault",
    "vault_name",
    default=None,
    help=(
        "Vault name from ~/.config/litman/vaults.yaml. "
        "Mutually exclusive with --library."
    ),
)
def export_cmd(
    project: str | None,
    export_all: bool,
    output_path: Path | None,
    priority: str | None,
    status: str | None,
    year: str | None,
    type_filter: str | None,
    topic: str | None,
    method: str | None,
    data_filter: str | None,
    author: str | None,
    force: bool,
    fmt: str,
    library: Path | None,
    vault_name: str | None,
) -> None:
    """Project the vault out to a .bib file.

    Cite keys equal paper ids, so a freshly-exported bibliography
    works with \\cite{<paper-id>} immediately. Re-running the
    command on the same file is the supported update path.
    """
    if export_all and project is not None:
        raise ExportError(
            "--project and --all are mutually exclusive. Pass exactly one."
        )
    if not export_all and project is None:
        raise ExportError(
            "Pass --project <name> or --all. Refusing to export with no scope "
            "(would silently flatten the whole vault into a single .bib)."
        )

    # fmt is reserved for future formats; M12 only ships bibtex. Click's
    # Choice already restricts the surface, so this is a defensive check.
    if fmt != "bibtex":  # pragma: no cover — Click prevents it today
        raise ExportError(f"Unsupported export format: {fmt!r}.")

    vault = find_vault(resolve_library_or_vault(library, vault_name))
    all_papers = list_papers(vault)

    # --project / --all is the scope gate enforced above. When --all is given,
    # project is None, so no project membership filter is applied; --project
    # NAME is wrapped in a single-element list and goes through the shared
    # list-membership filter like topics/methods/data.
    filters: dict[str, list[str] | None] = {
        "project": [project] if project is not None else None,
        "priority": split_csv(priority),
        "status": split_csv(status),
        "year": split_csv(year),
        "type": split_csv(type_filter),
        "topic": split_csv(topic),
        "method": split_csv(method),
        "data": split_csv(data_filter),
        "author": split_csv(author),
    }
    selected = [p for p in all_papers if matches_filters(p, filters)]
    # Sort by id for stable output (matches INDEX.json convention).
    selected.sort(key=lambda p: str(p.get("id", "")))

    target = (output_path or Path.cwd() / _DEFAULT_OUTPUT).resolve()

    # Sentinel-guarded overwrite: an existing target without our sentinel
    # is treated as user-owned and refused unless --force is given.
    if target.exists() and not force:
        existing = target.read_text(encoding="utf-8", errors="replace")
        if not has_sentinel(existing):
            raise ExportError(
                f"Refusing to overwrite {target}: file has no litman "
                "sentinel (looks hand-edited). Pass --force to overwrite "
                "anyway, or write to a different path with -o."
            )

    sentinel = _build_sentinel()
    content = emit_bib(selected, sentinel)

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")

    # emit_bib skips id-less papers (no cite key) rather than crash the whole
    # export (review F2); surface the drop so it is never silent.
    exported = [m for m in selected if m.get("id")]
    skipped_no_id = len(selected) - len(exported)

    scope = f"project={project!r}" if project else "all papers"
    console.print(
        f"[green]✓[/] Exported {len(exported)} paper"
        f"{'s' if len(exported) != 1 else ''} ({scope}) → "
        f"[bold]{target}[/]"
    )
    if skipped_no_id:
        console.print(
            f"[yellow]warning:[/] skipped {skipped_no_id} paper"
            f"{'s' if skipped_no_id != 1 else ''} with no id field "
            "(no bibtex cite key) — run `lit health-check`."
        )
    if not selected:
        # Not an error — an empty bib is a valid state (e.g. brand-new
        # project with no linked papers yet). Hint the user, though.
        console.print(
            "[dim]Note: no papers matched. The .bib has only the sentinel "
            "comment line.[/]"
        )
