"""Seed content for newly initialized literature vaults.

These templates are written verbatim by ``lit init`` (with library-name
substitution) into the new vault. They define the starting state of two
authoritative library-level files: ``TAXONOMY.md`` and ``lit-config.yaml``.

The third library-level file, ``INDEX.json``, is seeded by calling
``views.write_index(vault, [])`` so the empty form never drifts from the
regenerated form.

User-extensible TAXONOMY dictionaries (projects, topics, methods, data) start
empty; only the fixed enums (type, status, priority) are pre-populated. New
values are introduced via ``lit add`` or ``lit taxonomy add`` (M2).
"""

from __future__ import annotations

TAXONOMY_SEED = """\
# Literature Taxonomy

Controlled vocabulary for fields in `papers/<id>/metadata.yaml`. Edit user
dictionaries (projects, topics, methods, data) **only** via
`lit taxonomy {add,rename,merge,rm}` — hand-editing leaves dangling references
in existing metadata files.

## projects

(empty)

## topics

(empty)

## methods

(empty)

## data

(empty)

## type (fixed enum, not extensible)

- research
- review
- position
- benchmark
- dataset
- tutorial
- thesis
- book-chapter

## status (fixed enum, not extensible)

- deep-read
- skim
- inbox
- dropped

## priority (fixed enum, not extensible)

- A
- B
- C
"""


def render_lit_config_seed(library_name: str) -> str:
    """Render the initial ``lit-config.yaml`` body.

    Args:
        library_name: Value to set under the ``library_name`` key. Conventionally
            matches the vault subdirectory name.
    """
    return f"""\
# litman library configuration. Validated against `litman.config.LitConfig`
# (validation lands in M2). Edit by hand or via `lit config set` (M2+).

library_name: {library_name}
default_pdf_viewer: code

# View directories regenerated by `lit refresh-views` under views/.
view_definitions:
  - by-project
  - by-topic
  - by-method
  - by-status

# Fields used to detect duplicate papers during `lit add`.
unique_keys:
  - doi
  - arxiv-id
"""
