"""Seed content for newly initialized literature vaults.

These templates are written verbatim by ``lit init`` (with library-name
substitution) into the new vault. They define the starting state of two
authoritative library-level files: ``TAXONOMY.md`` and ``lit-config.yaml``.

The third library-level file, ``INDEX.json``, is seeded by calling
``views.write_index(vault, [])`` so the empty form never drifts from the
regenerated form.

User-extensible TAXONOMY dictionaries (projects, topics, methods, data) start
empty; only the fixed enums (type, status, priority) are pre-populated. New
values are introduced via ``lit add`` or ``lit taxonomy add`` (M2).
"""

from __future__ import annotations

TAXONOMY_SEED = """\
# Literature Taxonomy

Controlled vocabulary for fields in `papers/<id>/metadata.yaml`. Edit user
dictionaries (projects, topics, methods, data) **only** via
`lit taxonomy {add,rename,merge,rm}` — hand-editing leaves dangling references
in existing metadata files.

## projects

(empty)

## topics

(empty)

## methods

(empty)

## data

(empty)

## type (fixed enum, not extensible)

- research
- review
- position
- benchmark
- dataset
- tutorial
- thesis
- book-chapter

## status (fixed enum, not extensible)

- deep-read
- skim
- inbox
- dropped

## priority (fixed enum, not extensible)

- A
- B
- C
"""


def render_lit_config_seed(library_name: str) -> str:
    """Render the initial ``lit-config.yaml`` body.

    Field set matches ``litman.core.config.LitConfig``. Each field is given
    its schema default here so the on-disk form is self-documenting; older
    vaults whose yaml omits any of these still load because the schema
    supplies the same defaults.

    Args:
        library_name: Value to set under the ``library_name`` key. Conventionally
            matches the vault subdirectory name.
    """
    return f"""\
# litman library configuration. Validated against `litman.core.config.LitConfig`
# on every command that loads config. Edit by hand; `lit config show` prints
# the parsed view.

library_name: {library_name}
default_pdf_viewer: code

# View directories regenerated by `lit refresh-views` under views/.
view_definitions:
  - by-project
  - by-topic
  - by-method
  - by-status

# Fields used to detect duplicate papers during `lit add`.
unique_keys:
  - doi
  - arxiv-id

# Default --depth for `lit code add` / `lit code restore-all`. 0 = full history.
default_clone_depth: 1

# Glob patterns under codes/ that backup tools (rclone, etc.) should exclude
# from cloud sync. The bulky `repo/` checkout is re-clonable via
# `lit code restore-all`, so excluding it keeps the L2 backup small.
codes_ignore_patterns:
  - repo/

# Project name → project directory path. Consumed by `lit link/unlink` and
# the per-project REFERENCES.md regeneration step of `lit refresh-views`.
# Populate before linking papers, e.g.:
#   projects:
#     pepforge: /work/wangq/Project/PepForge
#     pepcodec: /work/wangq/Project/PepCodec
projects: {{}}
"""
