"""Derive INDEX.md and views/by-*/ from papers/*/metadata.yaml.

The metadata files are the single source of truth; INDEX.md and the
``views/by-{project,topic,method,status}/`` symlink hubs are regenerated
wholesale by ``lit refresh-views``. Symlinks are relative so that
``cp -r`` to a new machine still resolves them.
"""

from __future__ import annotations

import os
import shutil
from datetime import datetime
from pathlib import Path
from typing import Any

# Views whose tag values come from a list-typed metadata field.
LIST_VIEW_FIELDS: dict[str, str] = {
    "by-project": "projects",
    "by-topic": "topics",
    "by-method": "methods",
}

# Views whose tag values come from a single scalar metadata field.
SCALAR_VIEW_FIELDS: dict[str, str] = {
    "by-status": "status",
}


def _now_str() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M")


def _safe_name(value: str) -> str:
    return value.replace("/", "_").replace("\\", "_").strip()


def _format_list(values: list[str] | None) -> str:
    if not values:
        return "—"
    return ", ".join(values)


def _format_cell(value: Any) -> str:
    if value is None or value == "":
        return "—"
    return str(value)


def render_index(papers: list[dict[str, Any]], timestamp: str) -> str:
    """Render the INDEX.md content for a given paper list."""
    header = (
        "<!-- AUTO-GENERATED by `lit refresh-views` — DO NOT EDIT -->\n"
        f"<!-- Last updated: {timestamp} -->\n"
        "\n"
        "# Literature Index\n"
        "\n"
    )
    table_header = (
        "| id | year | type | priority | status | topics | projects | doi |\n"
        "|----|------|------|----------|--------|--------|----------|-----|\n"
    )

    if not papers:
        return (
            header
            + table_header
            + "\n(No papers yet. Run `lit add <pdf> --doi <doi>` to add the first one.)\n"
        )

    rows: list[str] = []
    for p in sorted(papers, key=lambda x: str(x.get("id", ""))):
        rows.append(
            "| {id} | {year} | {type} | {priority} | {status} | {topics} | {projects} | {doi} |".format(
                id=_format_cell(p.get("id")),
                year=_format_cell(p.get("year")),
                type=_format_cell(p.get("type")),
                priority=_format_cell(p.get("priority")),
                status=_format_cell(p.get("status")),
                topics=_format_list(p.get("topics")),
                projects=_format_list(p.get("projects")),
                doi=_format_cell(p.get("doi")),
            )
        )

    return header + table_header + "\n".join(rows) + "\n"


def write_index(vault: Path, papers: list[dict[str, Any]]) -> Path:
    """Write the rendered INDEX.md to ``<vault>/INDEX.md`` and return its path."""
    target = vault / "INDEX.md"
    target.write_text(render_index(papers, _now_str()), encoding="utf-8")
    return target


def _clear_view_subdir(view_dir: Path) -> None:
    """Empty (or create) a view bucket directory.

    Deletes both symlinks and tag-bucket subdirectories under ``view_dir``
    so that paper IDs / tag values no longer present in the metadata
    don't leave stale entries on disk.
    """
    if view_dir.exists():
        for child in view_dir.iterdir():
            if child.is_symlink() or child.is_file():
                child.unlink()
            elif child.is_dir():
                shutil.rmtree(child)
    else:
        view_dir.mkdir(parents=True, exist_ok=True)


def _make_relative_symlink(link_path: Path, target_path: Path) -> None:
    """Create a relative symlink at ``link_path`` pointing at ``target_path``.

    Both inputs are absolute paths; the symlink stores the relative form
    so that copying the entire vault to a new machine preserves resolution.
    """
    rel = os.path.relpath(target_path, link_path.parent)
    if link_path.is_symlink() or link_path.exists():
        link_path.unlink()
    link_path.symlink_to(rel)


def rebuild_views(
    vault: Path, papers: list[dict[str, Any]]
) -> dict[str, int]:
    """Rebuild ``views/by-*/`` symlink hubs from the given paper list.

    Returns a mapping ``{view_name: n_symlinks_created}`` for caller-side
    reporting.
    """
    views_dir = vault / "views"
    counts: dict[str, int] = {}

    for view_name, field_name in LIST_VIEW_FIELDS.items():
        view_dir = views_dir / view_name
        _clear_view_subdir(view_dir)
        n = 0
        for p in papers:
            paper_id = p.get("id")
            if not paper_id:
                continue
            for value in p.get(field_name) or []:
                bucket = view_dir / _safe_name(str(value))
                bucket.mkdir(parents=True, exist_ok=True)
                _make_relative_symlink(
                    bucket / paper_id, vault / "papers" / paper_id
                )
                n += 1
        counts[view_name] = n

    for view_name, field_name in SCALAR_VIEW_FIELDS.items():
        view_dir = views_dir / view_name
        _clear_view_subdir(view_dir)
        n = 0
        for p in papers:
            paper_id = p.get("id")
            value = p.get(field_name)
            if not paper_id or not value:
                continue
            bucket = view_dir / _safe_name(str(value))
            bucket.mkdir(parents=True, exist_ok=True)
            _make_relative_symlink(
                bucket / paper_id, vault / "papers" / paper_id
            )
            n += 1
        counts[view_name] = n

    return counts
