"""Derive INDEX.json and views/by-*/ from papers/*/metadata.yaml.

The metadata files are the single source of truth; INDEX.json and the
``views/by-{project,topic,method,status}/`` symlink hubs are regenerated
wholesale by ``lit refresh-views``. Symlinks are relative so that
``cp -r`` to a new machine still resolves them.

On filesystems that refuse symlinks (Windows without Developer Mode,
FAT32, etc.), the symlink hubs are silently skipped via
``core.portable_link``'s graceful-degrade contract (ADR-005). INDEX.json
and metadata.yaml stay authoritative regardless.

INDEX.json is consumed primarily by AI assistants and programmatic tooling.
Humans should browse via ``lit list`` (filterable, paginated) instead of
opening the JSON directly. JSON has no native comment syntax, so the
``_comment`` field carries the auto-generated banner.
"""

from __future__ import annotations

import json
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from litman.core.portable_link import make_relative_symlink

# Views whose tag values come from a list-typed metadata field.
LIST_VIEW_FIELDS: dict[str, str] = {
    "by-project": "projects",
    "by-topic": "topics",
    "by-method": "methods",
}

# Views whose tag values come from a single scalar metadata field.
SCALAR_VIEW_FIELDS: dict[str, str] = {
    "by-status": "status",
}

# Per-paper fields included in INDEX.json. A summary projection of
# metadata.yaml — AI consumers can `cat` the source file for fields not
# listed here.
INDEX_PAPER_FIELDS: tuple[str, ...] = (
    "id",
    "title",
    "year",
    "type",
    "priority",
    "status",
    "topics",
    "projects",
    "methods",
    "doi",
)

# Fields stored as lists in metadata.yaml — emitted as `[]` when absent so
# downstream consumers don't have to special-case None.
_LIST_FIELDS = {"topics", "projects", "methods"}


def _now_iso() -> str:
    """Local-timezone ISO 8601 timestamp with seconds precision."""
    return datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")


def _safe_name(value: str) -> str:
    return value.replace("/", "_").replace("\\", "_").strip()


def _project_paper(p: dict[str, Any]) -> dict[str, Any]:
    """Pick the INDEX.json subset of fields from a metadata dict."""
    out: dict[str, Any] = {}
    for field in INDEX_PAPER_FIELDS:
        value = p.get(field)
        if field in _LIST_FIELDS:
            out[field] = list(value) if value else []
        else:
            out[field] = value
    return out


def _build_by_doi(papers: list[dict[str, Any]]) -> dict[str, str]:
    """Build the ``by_doi`` reverse map: normalized DOI → paper id.

    DOIs are case-insensitive per the DOI Handbook; normalized to lowercase
    + stripped so future ``lit show --doi`` / AI lookups can hit without
    normalizing again. Last-write wins on collisions, but a vault with two
    papers sharing one DOI is already a health-check violation surfaced by
    M2.8 — this map is best-effort, not the dedup source of truth.
    """
    # Local import avoids a hard import cycle when views.py is imported during
    # library.create_vault() before dedup's heavier ruamel-typ machinery loads.
    from litman.core.dedup import normalize_doi

    out: dict[str, str] = {}
    for p in papers:
        doi = p.get("doi")
        paper_id = p.get("id")
        if not doi or not paper_id:
            continue
        key = normalize_doi(str(doi))
        if not key:
            continue
        out[key] = str(paper_id)
    return out


def render_index(papers: list[dict[str, Any]], timestamp: str) -> str:
    """Render the INDEX.json content for a given paper list.

    Returns a JSON string with stable key order, two-space indent, and
    UTF-8 characters preserved (no ``\\uXXXX`` escapes) so the file stays
    readable for AI consumers.
    """
    sorted_papers = sorted(papers, key=lambda x: str(x.get("id", "")))
    payload = {
        "_comment": "AUTO-GENERATED by `lit refresh-views` — DO NOT EDIT BY HAND",
        "generated_at": timestamp,
        "n_papers": len(sorted_papers),
        "papers": [_project_paper(p) for p in sorted_papers],
        "by_doi": _build_by_doi(sorted_papers),
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def write_index(vault: Path, papers: list[dict[str, Any]]) -> Path:
    """Write the rendered INDEX.json to ``<vault>/INDEX.json`` and return its path."""
    target = vault / "INDEX.json"
    target.write_text(render_index(papers, _now_iso()), encoding="utf-8")
    return target


def _clear_view_subdir(view_dir: Path) -> None:
    """Empty (or create) a view bucket directory.

    Deletes both symlinks and tag-bucket subdirectories under ``view_dir``
    so that paper IDs / tag values no longer present in the metadata
    don't leave stale entries on disk.
    """
    if view_dir.exists():
        for child in view_dir.iterdir():
            if child.is_symlink() or child.is_file():
                child.unlink()
            elif child.is_dir():
                shutil.rmtree(child)
    else:
        view_dir.mkdir(parents=True, exist_ok=True)


def rebuild_views(
    vault: Path, papers: list[dict[str, Any]]
) -> dict[str, int]:
    """Rebuild ``views/by-*/`` symlink hubs from the given paper list.

    Returns a mapping ``{view_name: n_symlinks_created}`` for caller-side
    reporting. On platforms where symlink creation is refused (Windows
    without dev mode, FAT32, etc.), individual entries are silently
    skipped — the count reflects actual symlinks created, not requested.
    A one-shot warning is emitted by ``portable_link`` on first failure.
    """
    views_dir = vault / "views"
    counts: dict[str, int] = {}

    for view_name, field_name in LIST_VIEW_FIELDS.items():
        view_dir = views_dir / view_name
        _clear_view_subdir(view_dir)
        n = 0
        for p in papers:
            paper_id = p.get("id")
            if not paper_id:
                continue
            for value in p.get(field_name) or []:
                bucket = view_dir / _safe_name(str(value))
                bucket.mkdir(parents=True, exist_ok=True)
                if make_relative_symlink(
                    bucket / paper_id, vault / "papers" / paper_id
                ):
                    n += 1
        counts[view_name] = n

    for view_name, field_name in SCALAR_VIEW_FIELDS.items():
        view_dir = views_dir / view_name
        _clear_view_subdir(view_dir)
        n = 0
        for p in papers:
            paper_id = p.get("id")
            value = p.get(field_name)
            if not paper_id or not value:
                continue
            bucket = view_dir / _safe_name(str(value))
            bucket.mkdir(parents=True, exist_ok=True)
            if make_relative_symlink(
                bucket / paper_id, vault / "papers" / paper_id
            ):
                n += 1
        counts[view_name] = n

    return counts
