"""Unit tests for the INDEX projection (``core/views.py``).

Covers the M31 change (``read-date`` joins ``INDEX_PAPER_FIELDS`` as a
scalar: absent -> null, NOT []) and the v1.1.1 revision: ``authors`` joins
the thin projection as a list field (absent -> []) so the GUI quick-search
and ``lit list --format json`` consumers can match/read authors without a
per-paper load. ``created-at`` stays out (spec §7).
"""

from __future__ import annotations

import json
from datetime import date, datetime, timezone
from pathlib import Path

from litman.core.views import INDEX_PAPER_FIELDS, project_paper


def test_index_fields_contain_read_date() -> None:
    assert "read-date" in INDEX_PAPER_FIELDS


def test_index_fields_exclude_created_at() -> None:
    assert "created-at" not in INDEX_PAPER_FIELDS


def test_index_fields_contain_authors_as_list_field() -> None:
    # v1.1.1: authors joined the projection. List semantics — absent -> [].
    assert "authors" in INDEX_PAPER_FIELDS
    assert project_paper({"id": "p1"})["authors"] == []
    assert project_paper({"id": "p1", "authors": ["Smith, J."]})["authors"] == [
        "Smith, J."
    ]


def test_project_paper_passes_through_read_date() -> None:
    paper = {"id": "p1", "read-date": "2026-05-10"}
    out = project_paper(paper)
    assert "read-date" in out
    assert out["read-date"] == "2026-05-10"


def test_project_paper_coerces_date_object_to_iso_string() -> None:
    # The YAML safe-loader yields a datetime.date for read-date; the
    # projection must coerce it to a YYYY-MM-DD string so json.dumps works.
    out = project_paper({"id": "p1", "read-date": date(2026, 5, 1)})
    assert out["read-date"] == "2026-05-01"
    # Round-trips through json without raising (the bug this guards against).
    json.dumps(out)


def test_project_paper_coerces_datetime_to_calendar_date() -> None:
    out = project_paper(
        {"id": "p1", "read-date": datetime(2026, 5, 1, 9, 0, tzinfo=timezone.utc)}
    )
    assert out["read-date"] == "2026-05-01"
    json.dumps(out)


def test_project_paper_absent_read_date_is_none_not_empty_list() -> None:
    # read-date is a scalar field, so an absent value must become null
    # (None), never [] (which is reserved for the list-typed fields).
    out = project_paper({"id": "p1"})
    assert "read-date" in out
    assert out["read-date"] is None
    assert out["read-date"] != []


def test_project_paper_key_set_equals_index_fields() -> None:
    # The projection's key set must stay byte-identical to INDEX_PAPER_FIELDS
    # (the single source both `lit list --format json` and INDEX.json use).
    out = project_paper({"id": "p1", "year": 2024})
    assert set(out.keys()) == set(INDEX_PAPER_FIELDS)


def test_project_paper_key_order_is_index_fields_order() -> None:
    # The projection emits keys in INDEX_PAPER_FIELDS order, and a new field
    # is *appended*, never inserted: an INDEX.json regenerated by a newer
    # litman then differs from the old one only by added lines, which is what
    # keeps the file diffable and its key order predictable. (This test began
    # as "read-date is the last key"; `updated-at` was appended after it for
    # recency ranking, and the rule — not the specific tail — is the point.)
    out = project_paper({"id": "p1"})
    assert tuple(out.keys()) == INDEX_PAPER_FIELDS
    assert INDEX_PAPER_FIELDS[:13] == (
        "id",
        "title",
        "authors",
        "year",
        "type",
        "priority",
        "status",
        "topics",
        "projects",
        "methods",
        "data",
        "doi",
        "read-date",
    )
    assert INDEX_PAPER_FIELDS[-1] == "updated-at"


def test_project_paper_keeps_updated_at_time_of_day() -> None:
    # updated-at drives recency ranking, so unlike read-date it must NOT be
    # truncated to a calendar date — two papers edited on the same day have
    # to stay orderable. The YAML safe-loader hands us a datetime; the
    # projection must serialize it JSON-clean without losing the clock.
    out = project_paper(
        {
            "id": "p1",
            "updated-at": datetime(2026, 5, 1, 9, 30, 15, tzinfo=timezone.utc),
        }
    )
    assert out["updated-at"] == "2026-05-01T09:30:15+00:00"
    json.dumps(out)  # the bug this guards against: datetime is not JSON


def test_project_paper_updated_at_round_trips_to_the_same_instant() -> None:
    # The contract that lets the INDEX serve the reading view: whatever
    # recency_key computes from the typed object a live scan hands it, it must
    # also compute from the string the projection wrote. Not "close" — equal.
    from litman.core.query import recency_key

    for raw in (
        datetime(2026, 5, 1, 9, 30, 15, tzinfo=timezone.utc),
        datetime(2026, 5, 1, 9, 30, 15),  # naive (local)
        date(2026, 5, 1),  # under-specified value in the yaml
    ):
        scanned = {"id": "p1", "updated-at": raw}
        projected = project_paper(scanned)
        vault = Path("/nonexistent")  # no paper.pdf → mtime side is 0.0
        assert recency_key(vault, projected) == recency_key(vault, scanned)
