"""Tests for per-project REFERENCES.md generator (M5.1)."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest
from click.testing import CliRunner
from ruamel.yaml import YAML

from litman.cli import cli
from litman.core.library import create_vault
from litman.core.project_refs import (
    LITERATURE_SUBDIR,
    REFERENCES_FILENAME,
    rebuild_all_project_refs,
    render_references_md,
    write_references_md,
)

_yaml = YAML()
_yaml.indent(mapping=2, sequence=4, offset=2)
_yaml.default_flow_style = False


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def vault(tmp_path: Path) -> Path:
    return create_vault(tmp_path)


def _make_paper(
    vault: Path,
    paper_id: str,
    *,
    title: str = "Test paper",
    year: int | None = 2024,
    authors: list[str] | None = None,
    priority: str | None = "B",
    projects: list[str] | None = None,
    **extra: Any,
) -> Path:
    paper_dir = vault / "papers" / paper_id
    paper_dir.mkdir(parents=True, exist_ok=True)
    meta = {
        "id": paper_id,
        "title": title,
        "authors": authors or ["Doe, Jane"],
        "year": year,
        "doi": f"10.test/{paper_id}",
        "status": "inbox",
        "priority": priority,
        "type": "research",
        "projects": projects or [],
        "topics": [],
        "methods": [],
        "code-clones": [],
        "created-at": "2026-05-11T10:00:00+02:00",
        "updated-at": "2026-05-11T10:00:00+02:00",
        **extra,
    }
    with (paper_dir / "metadata.yaml").open("w", encoding="utf-8") as f:
        _yaml.dump(meta, f)
    return paper_dir


# ---------------------------------------------------------------------------
# render_references_md
# ---------------------------------------------------------------------------


def test_render_banner_present(vault: Path) -> None:
    out = render_references_md(vault, "pepforge", now="2026-05-11T15:00:00+02:00")
    assert out.startswith(
        "<!-- AUTO-GENERATED by `lit refresh-views` — DO NOT EDIT -->"
    )
    assert "Last updated: 2026-05-11T15:00:00+02:00" in out


def test_render_empty_project_message(vault: Path) -> None:
    """No papers tagged with project -> friendly message, no priority sections."""
    _make_paper(vault, "2024_Doe_Other", projects=["different"])
    out = render_references_md(vault, "pepforge")
    assert "No papers tagged" in out
    assert "lit modify <id> --add-tag projects=pepforge" in out
    assert "## Priority" not in out


def test_render_groups_by_priority(vault: Path) -> None:
    _make_paper(vault, "2024_A_paper", projects=["pepforge"], priority="A")
    _make_paper(vault, "2023_B_paper", projects=["pepforge"], priority="B")
    _make_paper(vault, "2022_C_paper", projects=["pepforge"], priority="C")
    out = render_references_md(vault, "pepforge")
    # A appears before B which appears before C.
    a_pos = out.index("Priority A")
    b_pos = out.index("Priority B")
    c_pos = out.index("Priority C")
    assert a_pos < b_pos < c_pos


def test_render_unprioritized_bucket_last(vault: Path) -> None:
    _make_paper(vault, "2024_A_paper", projects=["pepforge"], priority="A")
    _make_paper(vault, "2023_X_paper", projects=["pepforge"], priority=None)
    out = render_references_md(vault, "pepforge")
    a_pos = out.index("Priority A")
    u_pos = out.index("Unprioritized")
    assert a_pos < u_pos


def test_render_year_desc_within_group(vault: Path) -> None:
    _make_paper(vault, "2020_Older_paper", projects=["pepforge"], priority="A", year=2020)
    _make_paper(vault, "2024_Newer_paper", projects=["pepforge"], priority="A", year=2024)
    out = render_references_md(vault, "pepforge")
    newer = out.index("2024_Newer_paper")
    older = out.index("2020_Older_paper")
    assert newer < older  # newer year listed first


def test_render_authors_truncation() -> None:
    """1 author -> just the family; 2 -> both families; 3+ -> first two + 'et al.'"""
    from litman.core.project_refs import _format_authors
    assert _format_authors(["Doe, J."]) == "Doe"
    assert _format_authors(["Doe, J.", "Roe, K."]) == "Doe, Roe"
    assert _format_authors(["A, x", "B, y", "C, z", "D, w"]) == "A, B et al."


def test_render_relevance_annotation_present(vault: Path) -> None:
    _make_paper(
        vault, "2024_X_paper",
        projects=["pepforge"],
        priority="A",
        **{"relevance-pepforge": "Direct baseline; PEPTIDE-only case."},
    )
    out = render_references_md(vault, "pepforge")
    assert "*Direct baseline; PEPTIDE-only case.*" in out


def test_render_relevance_for_wrong_project_ignored(vault: Path) -> None:
    """relevance-pepcodec should not bleed into pepforge's REFERENCES."""
    _make_paper(
        vault, "2024_X_paper",
        projects=["pepforge"],
        priority="A",
        **{"relevance-pepcodec": "Different-project note."},
    )
    out = render_references_md(vault, "pepforge")
    assert "Different-project note" not in out


def test_render_wikilink_format(vault: Path) -> None:
    """Each entry uses `[[id]]` per design doc §9.4."""
    _make_paper(vault, "2024_X_paper", projects=["pepforge"])
    out = render_references_md(vault, "pepforge")
    assert "`[[2024_X_paper]]`" in out


def test_render_year_missing_renders_nd(vault: Path) -> None:
    _make_paper(vault, "2024_X_paper", projects=["pepforge"], year=None)
    out = render_references_md(vault, "pepforge")
    assert "n.d." in out


def test_render_project_match_is_case_sensitive(vault: Path) -> None:
    """Case mismatch should NOT silently match — typos must surface."""
    _make_paper(vault, "2024_X_paper", projects=["PepForge"])
    out = render_references_md(vault, "pepforge")
    assert "No papers tagged" in out


def test_render_count_in_header(vault: Path) -> None:
    _make_paper(vault, "p1", projects=["pepforge"], priority="A")
    _make_paper(vault, "p2", projects=["pepforge"], priority="B")
    out = render_references_md(vault, "pepforge")
    assert "**2 papers**" in out


def test_render_single_paper_singular(vault: Path) -> None:
    _make_paper(vault, "p1", projects=["pepforge"], priority="A")
    out = render_references_md(vault, "pepforge")
    assert "**1 paper**" in out


# ---------------------------------------------------------------------------
# write_references_md
# ---------------------------------------------------------------------------


def test_write_creates_literature_subdir(vault: Path, tmp_path: Path) -> None:
    project_dir = tmp_path / "pepforge_proj"
    project_dir.mkdir()
    _make_paper(vault, "p1", projects=["pepforge"])
    target = write_references_md(vault, "pepforge", project_dir)
    assert target == project_dir / LITERATURE_SUBDIR / REFERENCES_FILENAME
    assert target.is_file()
    assert (project_dir / LITERATURE_SUBDIR).is_dir()


def test_write_idempotent(vault: Path, tmp_path: Path) -> None:
    project_dir = tmp_path / "pepforge_proj"
    project_dir.mkdir()
    _make_paper(vault, "p1", projects=["pepforge"])
    first = write_references_md(vault, "pepforge", project_dir, now="2026-05-11T01:00:00+02:00")
    second = write_references_md(vault, "pepforge", project_dir, now="2026-05-11T02:00:00+02:00")
    assert first == second
    # Body differs only in the timestamp banner — content is otherwise stable.
    assert second.read_text(encoding="utf-8").count("Priority B") == 1


def test_write_refuses_missing_project_dir(vault: Path, tmp_path: Path) -> None:
    with pytest.raises(FileNotFoundError):
        write_references_md(vault, "pepforge", tmp_path / "does_not_exist")


# ---------------------------------------------------------------------------
# rebuild_all_project_refs
# ---------------------------------------------------------------------------


def test_rebuild_all_writes_each_registered_project(vault: Path, tmp_path: Path) -> None:
    pf_dir = tmp_path / "pepforge_proj"
    pf_dir.mkdir()
    pc_dir = tmp_path / "pepcodec_proj"
    pc_dir.mkdir()

    _make_paper(vault, "p1", projects=["pepforge"])
    _make_paper(vault, "p2", projects=["pepcodec"])
    _make_paper(vault, "p3", projects=["pepforge", "pepcodec"])  # shared

    results = rebuild_all_project_refs(
        vault, {"pepforge": str(pf_dir), "pepcodec": str(pc_dir)}
    )
    assert set(results.keys()) == {"pepforge", "pepcodec"}
    assert results["pepforge"]["status"] == "written"
    assert results["pepcodec"]["status"] == "written"
    assert results["pepforge"]["n_papers"] == 2
    assert results["pepcodec"]["n_papers"] == 2
    assert (pf_dir / "litman_reflib" / "REFERENCES.md").is_file()
    assert (pc_dir / "litman_reflib" / "REFERENCES.md").is_file()


def test_rebuild_all_skips_missing_project_dir(vault: Path, tmp_path: Path) -> None:
    """Project dir absent on this machine -> skip, don't abort the loop."""
    pf_dir = tmp_path / "pepforge_proj"
    pf_dir.mkdir()
    _make_paper(vault, "p1", projects=["pepforge"])
    _make_paper(vault, "p2", projects=["nowhere"])

    results = rebuild_all_project_refs(
        vault,
        {
            "pepforge": str(pf_dir),
            "nowhere": str(tmp_path / "does_not_exist"),
        },
    )
    assert results["pepforge"]["status"] == "written"
    assert results["nowhere"]["status"] == "skipped"
    assert "not found" in results["nowhere"]["detail"]
    # Still counts paper tagged with the missing project so user knows.
    assert results["nowhere"]["n_papers"] == 1


def test_rebuild_all_empty_registry(vault: Path) -> None:
    _make_paper(vault, "p1", projects=["pepforge"])
    results = rebuild_all_project_refs(vault, {})
    assert results == {}


def test_rebuild_all_expands_tilde(vault: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """``~`` in the registry path is expanded relative to HOME."""
    monkeypatch.setenv("HOME", str(tmp_path))
    pf_dir = tmp_path / "pepforge_proj"
    pf_dir.mkdir()
    _make_paper(vault, "p1", projects=["pepforge"])

    results = rebuild_all_project_refs(
        vault, {"pepforge": "~/pepforge_proj"}
    )
    assert results["pepforge"]["status"] == "written"
    assert (pf_dir / "litman_reflib" / "REFERENCES.md").is_file()


# ---------------------------------------------------------------------------
# CLI integration: lit refresh-views regenerates project REFERENCES.md
# ---------------------------------------------------------------------------


def _write_config(vault: Path, projects: dict[str, str]) -> None:
    cfg = vault / "lit-config.yaml"
    lines = [
        f"library_name: {vault.name}",
        "projects:",
    ]
    for name, path in projects.items():
        lines.append(f"  {name}: {path}")
    cfg.write_text("\n".join(lines) + "\n", encoding="utf-8")


def test_cli_refresh_views_writes_project_refs(vault: Path, tmp_path: Path) -> None:
    pf_dir = tmp_path / "pepforge_proj"
    pf_dir.mkdir()
    _write_config(vault, {"pepforge": str(pf_dir)})
    _make_paper(vault, "p1", projects=["pepforge"], priority="A")

    runner = CliRunner()
    result = runner.invoke(cli, ["refresh-views", "--library", str(vault)])
    assert result.exit_code == 0, result.output
    assert "Project REFERENCES.md" in result.output
    assert "pepforge: 1 paper" in result.output
    target = pf_dir / "litman_reflib" / "REFERENCES.md"
    assert target.is_file()
    body = target.read_text(encoding="utf-8")
    assert "p1" in body
    assert "Priority A" in body


def test_cli_refresh_views_no_projects_no_section(vault: Path) -> None:
    """When config has empty `projects: {}` the project block is silent."""
    runner = CliRunner()
    result = runner.invoke(cli, ["refresh-views", "--library", str(vault)])
    assert result.exit_code == 0, result.output
    assert "Project REFERENCES.md" not in result.output


def test_cli_refresh_views_skipped_project_reported(
    vault: Path, tmp_path: Path
) -> None:
    _write_config(vault, {"ghost": str(tmp_path / "does_not_exist")})
    _make_paper(vault, "p1", projects=["ghost"])

    runner = CliRunner()
    result = runner.invoke(cli, ["refresh-views", "--library", str(vault)])
    assert result.exit_code == 0, result.output
    assert "skipped" in result.output
    assert "ghost" in result.output
